# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/INTRANET/shmichel/myfiles/3emesemestre/Projet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/INTRANET/shmichel/myfiles/3emesemestre/Projet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/INTRANET/shmichel/myfiles/3emesemestre/Projet/CMakeFiles /home/INTRANET/shmichel/myfiles/3emesemestre/Projet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/INTRANET/shmichel/myfiles/3emesemestre/Projet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named neuron

# Build rule for target.
neuron: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 neuron
.PHONY : neuron

# fast build rule for target.
neuron/fast:
	$(MAKE) -f CMakeFiles/neuron.dir/build.make CMakeFiles/neuron.dir/build
.PHONY : neuron/fast

#=============================================================================
# Target rules for targets named neurone

# Build rule for target.
neurone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 neurone
.PHONY : neurone

# fast build rule for target.
neurone/fast:
	$(MAKE) -f CMakeFiles/neurone.dir/build.make CMakeFiles/neurone.dir/build
.PHONY : neurone/fast

#=============================================================================
# Target rules for targets named neurone_unittest

# Build rule for target.
neurone_unittest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 neurone_unittest
.PHONY : neurone_unittest

# fast build rule for target.
neurone_unittest/fast:
	$(MAKE) -f CMakeFiles/neurone_unittest.dir/build.make CMakeFiles/neurone_unittest.dir/build
.PHONY : neurone_unittest/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f gtest/CMakeFiles/gtest.dir/build.make gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f gtest/CMakeFiles/gtest_main.dir/build.make gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

Neuron.o: Neuron.cpp.o
.PHONY : Neuron.o

# target to build an object file
Neuron.cpp.o:
	$(MAKE) -f CMakeFiles/neuron.dir/build.make CMakeFiles/neuron.dir/Neuron.cpp.o
	$(MAKE) -f CMakeFiles/neurone.dir/build.make CMakeFiles/neurone.dir/Neuron.cpp.o
	$(MAKE) -f CMakeFiles/neurone_unittest.dir/build.make CMakeFiles/neurone_unittest.dir/Neuron.cpp.o
.PHONY : Neuron.cpp.o

Neuron.i: Neuron.cpp.i
.PHONY : Neuron.i

# target to preprocess a source file
Neuron.cpp.i:
	$(MAKE) -f CMakeFiles/neuron.dir/build.make CMakeFiles/neuron.dir/Neuron.cpp.i
	$(MAKE) -f CMakeFiles/neurone.dir/build.make CMakeFiles/neurone.dir/Neuron.cpp.i
	$(MAKE) -f CMakeFiles/neurone_unittest.dir/build.make CMakeFiles/neurone_unittest.dir/Neuron.cpp.i
.PHONY : Neuron.cpp.i

Neuron.s: Neuron.cpp.s
.PHONY : Neuron.s

# target to generate assembly for a file
Neuron.cpp.s:
	$(MAKE) -f CMakeFiles/neuron.dir/build.make CMakeFiles/neuron.dir/Neuron.cpp.s
	$(MAKE) -f CMakeFiles/neurone.dir/build.make CMakeFiles/neurone.dir/Neuron.cpp.s
	$(MAKE) -f CMakeFiles/neurone_unittest.dir/build.make CMakeFiles/neurone_unittest.dir/Neuron.cpp.s
.PHONY : Neuron.cpp.s

Simulation.o: Simulation.cpp.o
.PHONY : Simulation.o

# target to build an object file
Simulation.cpp.o:
	$(MAKE) -f CMakeFiles/neuron.dir/build.make CMakeFiles/neuron.dir/Simulation.cpp.o
	$(MAKE) -f CMakeFiles/neurone.dir/build.make CMakeFiles/neurone.dir/Simulation.cpp.o
	$(MAKE) -f CMakeFiles/neurone_unittest.dir/build.make CMakeFiles/neurone_unittest.dir/Simulation.cpp.o
.PHONY : Simulation.cpp.o

Simulation.i: Simulation.cpp.i
.PHONY : Simulation.i

# target to preprocess a source file
Simulation.cpp.i:
	$(MAKE) -f CMakeFiles/neuron.dir/build.make CMakeFiles/neuron.dir/Simulation.cpp.i
	$(MAKE) -f CMakeFiles/neurone.dir/build.make CMakeFiles/neurone.dir/Simulation.cpp.i
	$(MAKE) -f CMakeFiles/neurone_unittest.dir/build.make CMakeFiles/neurone_unittest.dir/Simulation.cpp.i
.PHONY : Simulation.cpp.i

Simulation.s: Simulation.cpp.s
.PHONY : Simulation.s

# target to generate assembly for a file
Simulation.cpp.s:
	$(MAKE) -f CMakeFiles/neuron.dir/build.make CMakeFiles/neuron.dir/Simulation.cpp.s
	$(MAKE) -f CMakeFiles/neurone.dir/build.make CMakeFiles/neurone.dir/Simulation.cpp.s
	$(MAKE) -f CMakeFiles/neurone_unittest.dir/build.make CMakeFiles/neurone_unittest.dir/Simulation.cpp.s
.PHONY : Simulation.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/neuron.dir/build.make CMakeFiles/neuron.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/neurone.dir/build.make CMakeFiles/neurone.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/neuron.dir/build.make CMakeFiles/neuron.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/neurone.dir/build.make CMakeFiles/neurone.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/neuron.dir/build.make CMakeFiles/neuron.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/neurone.dir/build.make CMakeFiles/neurone.dir/main.cpp.s
.PHONY : main.cpp.s

unittest.o: unittest.cpp.o
.PHONY : unittest.o

# target to build an object file
unittest.cpp.o:
	$(MAKE) -f CMakeFiles/neurone_unittest.dir/build.make CMakeFiles/neurone_unittest.dir/unittest.cpp.o
.PHONY : unittest.cpp.o

unittest.i: unittest.cpp.i
.PHONY : unittest.i

# target to preprocess a source file
unittest.cpp.i:
	$(MAKE) -f CMakeFiles/neurone_unittest.dir/build.make CMakeFiles/neurone_unittest.dir/unittest.cpp.i
.PHONY : unittest.cpp.i

unittest.s: unittest.cpp.s
.PHONY : unittest.s

# target to generate assembly for a file
unittest.cpp.s:
	$(MAKE) -f CMakeFiles/neurone_unittest.dir/build.make CMakeFiles/neurone_unittest.dir/unittest.cpp.s
.PHONY : unittest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... neuron"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... neurone"
	@echo "... neurone_unittest"
	@echo "... test"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... Neuron.o"
	@echo "... Neuron.i"
	@echo "... Neuron.s"
	@echo "... Simulation.o"
	@echo "... Simulation.i"
	@echo "... Simulation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... unittest.o"
	@echo "... unittest.i"
	@echo "... unittest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

